# Generated by Django 4.1.7 on 2023-05-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_invitationcode_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationcode",
            name="code",
            field=models.CharField(default="qbcplmbe", max_length=100, unique=True),
        ),
    ]
