# Generated by Django 4.2.1 on 2023-05-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_invitationcode_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationcode",
            name="code",
            field=models.CharField(default="gpmdzlai", max_length=100, unique=True),
        ),
    ]
