# Generated by Django 4.1.7 on 2023-05-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_invitationcode_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationcode",
            name="code",
            field=models.CharField(default="yrebdcdw", max_length=100, unique=True),
        ),
    ]
