# Generated by Django 4.2.2 on 2023-09-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_invitationcode_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationcode",
            name="code",
            field=models.CharField(default="xdyzoyuh", max_length=100, unique=True),
        ),
    ]
