# Generated by Django 4.1.7 on 2023-09-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_invitationcode_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationcode",
            name="code",
            field=models.CharField(default="nwoknsqf", max_length=100, unique=True),
        ),
    ]
