# Generated by Django 4.1.7 on 2024-05-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_alter_invitationcode_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationcode",
            name="code",
            field=models.CharField(default="quxdyyaf", max_length=100, unique=True),
        ),
    ]
