# Generated by Django 4.1.7 on 2024-06-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_alter_invitationcode_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationcode",
            name="code",
            field=models.CharField(default="vbyxxrqk", max_length=100, unique=True),
        ),
    ]
