# Generated by Django 5.1.3 on 2024-11-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_alter_invitationcode_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationcode",
            name="code",
            field=models.CharField(default="ybvmfcvr", max_length=100, unique=True),
        ),
    ]
