# Generated by Django 4.1.7 on 2023-05-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retimgeval", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="delay_time",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
