# Generated by Django 4.2.1 on 2023-05-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retimgeval", "0002_answer_delay_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="alias",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
