# Generated by Django 4.2.1 on 2023-07-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retimgeval", "0004_question_image1_height_question_image1_width_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image4",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="question",
            name="image4_height",
            field=models.PositiveIntegerField(default=256),
        ),
        migrations.AddField(
            model_name="question",
            name="image4_width",
            field=models.PositiveIntegerField(default=256),
        ),
        migrations.AddField(
            model_name="question",
            name="image5",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="question",
            name="image5_height",
            field=models.PositiveIntegerField(default=256),
        ),
        migrations.AddField(
            model_name="question",
            name="image5_width",
            field=models.PositiveIntegerField(default=256),
        ),
    ]
