# Generated by Django 4.2.2 on 2023-09-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retimgeval", "0005_question_image4_question_image4_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image1_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="image2_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
