# Generated by Django 4.1.7 on 2023-09-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("retimgeval", "0007_question_image3_title_question_image4_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="question",
        ),
        migrations.CreateModel(
            name="SubQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=200, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="retimgeval.question",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="answer",
            name="sub_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="retimgeval.subquestion",
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="sub_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="retimgeval.subquestion",
            ),
        ),
    ]
