# Generated by Django 4.1.7 on 2023-09-08 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("retimgeval", "0008_remove_choice_question_subquestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="retimgeval.question",
            ),
        ),
    ]
