# Generated by Django 4.1.7 on 2024-05-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retimgeval", "0009_choice_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="image_height",
            field=models.PositiveIntegerField(default=256),
        ),
        migrations.AddField(
            model_name="choice",
            name="image_width",
            field=models.PositiveIntegerField(default=256),
        ),
    ]
