# Generated by Django 4.1.7 on 2024-05-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retimgeval", "0010_choice_image_height_choice_image_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="subquestion",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="subquestion",
            name="image_height",
            field=models.PositiveIntegerField(default=256),
        ),
        migrations.AddField(
            model_name="subquestion",
            name="image_width",
            field=models.PositiveIntegerField(default=256),
        ),
    ]
