# Generated by Django 4.1.7 on 2024-05-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retimgeval", "0011_subquestion_image_subquestion_image_height_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="image4",
        ),
        migrations.RemoveField(
            model_name="question",
            name="image4_height",
        ),
        migrations.RemoveField(
            model_name="question",
            name="image4_title",
        ),
        migrations.RemoveField(
            model_name="question",
            name="image4_width",
        ),
        migrations.RemoveField(
            model_name="question",
            name="image5",
        ),
        migrations.RemoveField(
            model_name="question",
            name="image5_height",
        ),
        migrations.RemoveField(
            model_name="question",
            name="image5_title",
        ),
        migrations.RemoveField(
            model_name="question",
            name="image5_width",
        ),
        migrations.AlterField(
            model_name="choice",
            name="image",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="image1",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="image2",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="image3",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="subquestion",
            name="image",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="images/"
            ),
        ),
    ]
