# Generated by Django 4.1.7 on 2024-06-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "retimgeval",
            "0012_remove_question_image4_remove_question_image4_height_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
