# Generated by Django 4.1.7 on 2023-05-22 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("retimgann", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="coordinates",
            field=models.JSONField(default=list),
        ),
        migrations.AlterUniqueTogether(
            name="annotation",
            unique_together={("user", "image")},
        ),
    ]
