# Generated by Django 4.2.1 on 2023-05-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retimgann", "0003_annotation_time_spent"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="index",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
