# Generated by Django 5.0.1 on 2024-01-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retimgann", "0005_annotation_mouse_trajectory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alias", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
