# Generated by Django 5.0.1 on 2024-01-24 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retimgann", "0007_add_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="task",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="retimgann.task",
            ),
            preserve_default=False,
        ),
    ]
