# Generated by Django 5.0.1 on 2024-01-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retimgann", "0008_image_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
